---
- name: restart ssh server
  systemd:
    state: restarted
    name: ssh
    enabled: yes
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: restart sshd server
  systemd:
    state: restarted
    name: sshd
    enabled: yes
  when:
    - ansible_os_family == "CentOS" or ansible_os_family == "RedHat"