- name: Config ipv4 forwarding
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: '^net.ipv4.ip_forward'
    line: net.ipv4.ip_forward = 1
  notify: sysctl_reload

- name: Update apt cache
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    
- name: Install OpenVPN and EasyRSA
  become: yes
  ansible.builtin.apt:
    name: 
      - openvpn
      - easy-rsa
    state: present

- name: Ensures needed dirs exist
  become: yes
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ easy_rsa_dir }}"
  
- name: Fixing dir permissions
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - "{{ client_config }}"
    - "{{ client_config }}/keys"
    - "{{ client_config }}/files"

- name: Copy easy-rsa to {{ config_root }}/easy-rsa
  become: yes
  ansible.builtin.copy:
    src: /usr/share/easy-rsa/
    dest: "{{ easy_rsa_dir }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700
    remote_src: yes

- name: Initialize pki
  command: ./easyrsa init-pki
  args:
    chdir: "{{ easy_rsa_dir }}"
    creates: "{{ easy_rsa_dir }}/pki"

- name: Copy pki vars
  template:
    src: vars.j2
    dest: "{{ easy_rsa_dir }}/vars"

- name: "Build CA keys"
  command: ./easyrsa --batch build-ca nopass
  args:
    chdir: "{{ easy_rsa_dir }}"
    creates: "{{ easy_rsa_dir }}/pki/ca.crt"

- name: Copy easy-rsa to {{ config_root }}/easy-rsa
  become: yes
  ansible.builtin.copy:
    src: "{{ easy_rsa_dir }}/pki/ca.crt"
    dest: /usr/local/share/ca-certificates/
    remote_src: yes

- name: Update CA certificates
  become: yes
  shell: /usr/sbin/update-ca-certificates

- name: Create req for server key
  command: ./easyrsa --batch gen-req server nopass
  args:
    chdir: "{{ easy_rsa_dir }}"
    creates: "{{ easy_rsa_dir }}/pki/reqs/server.req"

- name: Sign server.req
  command: ./easyrsa --batch sign-req server server
  args:
    chdir: "{{ easy_rsa_dir }}"
    creates: "{{ easy_rsa_dir }}/pki/issued/server.crt"

- name: Copy key to {{ openvpn_dir }}
  become: yes
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ openvpn_dir }}"
    remote_src: yes
  with_items:
    - "{{ easy_rsa_dir }}/pki/private/server.key"
    - "{{ easy_rsa_dir }}/pki/issued/server.crt"
    - "{{ easy_rsa_dir }}/pki/ca.crt"

- name: Create ta.key
  command: openvpn --genkey --secret ta.key
  args:
    chdir: "{{ easy_rsa_dir }}"
    creates: "{{ easy_rsa_dir }}/ta.key"

- name: Copy ta.key to {{ openvpn_dir }}
  become: yes
  ansible.builtin.copy:
    src: "{{ easy_rsa_dir }}/ta.key"
    dest: "{{ openvpn_dir }}"
    remote_src: yes

- name: Copy Server config file
  become: yes
  ansible.builtin.template:
    src: server.conf.j2
    dest: "{{ openvpn_dir }}/server.conf"
  notify: restart_openvpn

- name: Copy server cert and key to client dir
  become: yes
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ client_config }}/keys/"
    owner: "{{ user }}"
    group: "{{ user }}"
    remote_src: yes
  with_items:
    - "{{ openvpn_dir }}/ca.crt"
    - "{{ easy_rsa_dir }}/ta.key"

- name: Create script for user accounts
  ansible.builtin.copy:
    src: files/make_config.sh
    dest: "{{ client_config }}/make_config.sh"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: +x

- name: Copy base.conf
  ansible.builtin.template:
    src: base.conf.j2
    dest: "{{ client_config }}/base.conf"
    owner: "{{ user }}"
    group: "{{ user }}"