---
# ubuntu (debian)
# it uses 127.0.1.1 for hostname instead 127.0.0.1 (only localhost)

- name: changing hostname to match inventory_hostname
  shell: hostname {{ inventory_hostname }}; echo {{ inventory_hostname }} > /etc/hostname
  register: "hostname_status"
  become: true
  when: ansible_hostname != inventory_hostname

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1 {{ inventory_hostname_short }}'
    state: present
    owner: root
    group: root
    mode: '0644'